include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Error rules
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
  # removed: avoid_returning_null_for_future (obsolete on newer SDKs)
    avoid_type_to_string: true
    empty_statements: true
    prefer_final_locals: true
    prefer_final_fields: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
